version: "2"

volumes:
    nextcloud:
    db:

services:
    db:
        image: mariadb
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud

    app:
        image: nextcloud
        restart: always
        ports:
            - "127.0.0.1:8080:80"
        links:
            - db
        volumes:
            - nextcloud:/var/www/html
        environment:
            - MYSQL_PASSWORD=test
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_HOST=db
